/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagment.home;

/**
 *
 * @author User
 */
public class HomeView extends javax.swing.JFrame {
    private final HomeController hc = new HomeController();
    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItem = new javax.swing.JMenu();
        menuItemOut = new javax.swing.JMenuItem();
        menuData = new javax.swing.JMenu();
        menuItemBook = new javax.swing.JMenuItem();
        menuItemBorrowers = new javax.swing.JMenuItem();
        menuItemCategory = new javax.swing.JMenuItem();
        menuItemTransaction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuItem.setText("File");

        menuItemOut.setText("Logout");
        menuItemOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOutActionPerformed(evt);
            }
        });
        menuItem.add(menuItemOut);

        jMenuBar1.add(menuItem);

        menuData.setText("Data");

        menuItemBook.setText("Book");
        menuItemBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBookActionPerformed(evt);
            }
        });
        menuData.add(menuItemBook);

        menuItemBorrowers.setText("Borrowers");
        menuItemBorrowers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBorrowersActionPerformed(evt);
            }
        });
        menuData.add(menuItemBorrowers);

        menuItemCategory.setText("Category");
        menuItemCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCategoryActionPerformed(evt);
            }
        });
        menuData.add(menuItemCategory);

        menuItemTransaction.setText("Transaction");
        menuItemTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTransactionActionPerformed(evt);
            }
        });
        menuData.add(menuItemTransaction);

        jMenuBar1.add(menuData);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBookActionPerformed
        hc.menuItemBook(this);
    }//GEN-LAST:event_menuItemBookActionPerformed

    private void menuItemOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOutActionPerformed
        hc.exitMenuItemAction(this);
    }//GEN-LAST:event_menuItemOutActionPerformed

    private void menuItemTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTransactionActionPerformed
      hc.menuTransaction(this);
    }//GEN-LAST:event_menuItemTransactionActionPerformed

    private void menuItemCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCategoryActionPerformed
        hc.menuItemCategory(this);
    }//GEN-LAST:event_menuItemCategoryActionPerformed

    private void menuItemBorrowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBorrowersActionPerformed
        hc.menuItemBorrowers(this);
    }//GEN-LAST:event_menuItemBorrowersActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuData;
    private javax.swing.JMenu menuItem;
    public static javax.swing.JMenuItem menuItemBook;
    public static javax.swing.JMenuItem menuItemBorrowers;
    public static javax.swing.JMenuItem menuItemCategory;
    private javax.swing.JMenuItem menuItemOut;
    public static javax.swing.JMenuItem menuItemTransaction;
    public static javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
}
